<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFrameworks>net48;net6.0;netstandard2.0</TargetFrameworks>
    <SerilogVersion>2.10.0</SerilogVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
    <PackageReference Include="Dapper">
      <Version>2.0.123</Version>
    </PackageReference>
    <PackageReference Include="Serilog" Version="$(SerilogVersion)" />
    <PackageReference Include="Polly" Version="$(PollyVersion)" />
    <PackageReference Include="AutoMapper" Version="[10.0.0,11.0.0)" />
    <PackageReference Include="MediatR" Version="12.*" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="Azure.Identity" VersionOverride="1.10.2" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.118" PrivateAssets="all" />
    <PackageReference Include="jQuery" Version="3.4.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Core\Core.csproj" />
  </ItemGroup>
</Project>
